# Generated by Django 4.2.23 on 2025-08-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_user_address_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('MOTORBIKE', 'Xe máy'), ('CAR', 'Ô tô')], default='MOTORBIKE', max_length=20),
            preserve_default=False,
        ),
    ]
