# Generated by Django 4.2.23 on 2025-08-24 06:31

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('extra_embeddings', models.JSONField(help_text='Danh sách nhiều embeddings')),
                ('face_img', cloudinary.models.CloudinaryField(blank=True, help_text='Ảnh khuôn mặt', max_length=255, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='feerule',
            name='fee_type',
            field=models.CharField(choices=[('MOTORCYCLE', 'Xe máy'), ('CAR', 'Ô tô')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('MOTORCYCLE', 'Xe máy'), ('CAR', 'Ô tô')], max_length=20),
        ),
        migrations.AddField(
            model_name='parkinglog',
            name='user_face',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_logs', to='parking.userface'),
        ),
    ]
