# Generated by Django 4.2.23 on 2025-08-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_userface_alter_feerule_fee_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userface',
            name='extra_embeddings',
        ),
        migrations.AddField(
            model_name='userface',
            name='embedding',
            field=models.JSONField(default=[], help_text='embedding trung bình'),
            preserve_default=False,
        ),
    ]
